#!/bin/sh
# Pushes my website to trigeorgis.github.io

set -e
git checkout source
git branch -D master
git checkout -b master
git filter-branch --subdirectory-filter _site/ -f
git checkout source
git push --all origin
